### ISSUE TITLE
Promised features missing

### ISSUE THREAD

**Issue by AndruC** [HumanityInc/Humanity#1]

**Comment by Max-Human** [comment]
Andrew don't be a loser. :) <3

Why don't you HELP instead?? :)

- add friends button is underneath the music player in the beta (latest photos seen on HumanityTechnologies.com showcase a larger music player with no buttons underneath)

- instant messaging with text / pic / video is now part of beta. Additionally, live video HD calls, and sms and calls to any phone in the world, are coming to our site next month, and also next month to our apps on Android, iOS and Windows! :)

- Listen IS launching this week as promised. :)

P.S. Stop bitching; start helping. This is in reference to your last 10 posts. :) :) <3

**Comment by Max-Human** [comment]
Don't take this seriously man I am just kidding.. :) Late evening, still working away.. How are you man?? :)

**Comment by AndruC** [comment]
Just a little concerned, because I can't actually see these features anywhere in this codebase.

**Comment by Max-Human** [comment]
I have right now.. about 111 years (apparently?) to live. Enjoying my time man, with a little Bailey's + Absolut + 3.25% milk.. :)

FYI with respect to the code, a lot of our stuff hasn't been pushed to GitHub yet.. We don't wanna push unfinished code and then have people complain. :) So there is a ton of stuff that is 30%-80% finished, but not seen anywhere.. 

It will all be released in accordance with the release schedule though. We are going to make an infographic next week. For now the latest schedule is in the description of each video here (will be updated in few days): https://www.youtube.com/channel/UC3rBi2JifELqDVsy5YUSxhg

**Comment by AndruC** [comment]
"Enjoying my time man"

As the founder, shouldn't you be concerned with getting a product out as fast as possible? I mean, I'm sure the 101 existing users are loving the crowdfunding and the feed, though I'm very surprised I didn't get in, considering how many invitations were sent out, and how early I requested one. 

Oh well, this is an issue thread. Not really the time or place to discuss *that*.

**Comment by Max-Human** [comment]
Well, hell, I'm working 7 days a week, without a vacation for 3-4 years, without a weekend in probably 6-8 months, and GIVING AWAY all of my shares.. I mean EXCUSE ME if I'm not doing enough for ya.. :)

**Comment by Max-Human** [comment]
And, reminder: I GAVE UP RETIREMENT ON A BEACH IN LE MERIDIEN PHUKET THAILAND FOR THIS!!! :) <3

**Comment by Max-Human** [comment]
Andrew the Top 101 aren't actually enjoying ANYTHING.. :) Right now only a couple (literally) of people are in.. We are waiting on the 2nd half (bottom) of the top center menu, as seen on latest video on MaxHuman.me.. :) That is the instant notifications / instant messaging menu, and we wanna finish that before we let the rest of the top 101 in.. Also, before that happens, we wanna add some content.. :) So starting tomorrow, for the first 24 hours or so, our top 10 (or whatever) employees and volunteers will fill the network up with some CONTENT! :) Then the rest of the Top 101 get in.. Then in a week, the next 100, Then in a week, another 100. Then in a week, 250. Then in a week, 250, Then 500 for two weeks. Then 1000 for two weeks. Then 2500 for two weeks. You get the picture. :)

**Comment by AndruC** [comment]
> Well, hell, I'm working 7 days a week, without a vacation for 3-4 years

I understand that, though I don't necessarily understand what you actually *do* all day,other than be the "idea guy", and manage your dozens of social media entities.

**Comment by Max-Human** [comment]
Did you register with your real name? I don't remember seeing an Andrew on the list.. Otherwise I would have flagged your account for top 101.. :) Pls note that if you used a name like Asdasd (about 1% of registrees used a fake name), you will receive an email this week with a link to a form to change that. :) If your real name is now Andrew pls let me know and I will try to flag your account for top 101.. I know Masha had a problem where a few emails didn't work.. See, the first 200 people are people we know.. But for the 101 I think she was missing a few emails.. or something.. I can see if she can add yours. They will be getting their bright green account activation emails in the next 24-48 hrs. :)

**Comment by Max-Human** [comment]
What do I do all day,, Oh boy.. Good question.. :) Everything.. :) Same as everybody else here. There is a REASON we don't have job titles, and "equality" is not the #1 reason. The #1 reason is that everybody here wears a thousand hats. And will always wear. :) Because there is no reason to confine a CFO to being "STRICTLY" a CFO if he has OTHER talents for instance... It's like that for everybody here.. :) If you do accounting, you can also do ART!.. :)

**Comment by Max-Human** [comment]
Mrow. :)

**Comment by Max-Human** [comment]
(inside joke - see profile pic at fb.me/iammaxkit)

**Comment by AndruC** [comment]
OK, but... what's involved in "everything"? I mean, it can't be "everything", because you don't have any contributions to the git repo...

**Comment by Max-Human** [comment]
https://4.bp.blogspot.com/-Mmd4UWM2hzI/Ub9CFm_UkyI/AAAAAAAAAjQ/g770EUuhoqE/s1600/gun.png

Andrew..

I'm the guy..

Who GAVE YOU ALL THIS... :)

Now are you gonna sit there and keep pontificating or are you gonna GET OFF YOUR ASS AND HELP YOUR COMPANY??? :)

**Comment by Max-Human** [comment]
Honestly man, after EVERYTHING I've done for this company, after I sacrificed 3.5 years of my life, 10,000+ hours, my relationship, my retirement, my previous company.. after I gave up EVERYTHING for this company.. that I then gave away to YOU.. for YOU to QUESTION "my contribution".. having done NOTHING WHAT-SO-EVER for this company.. of which you will have the same exact one (1) full ownership & voting share as ME.. for you to question MY "contribution" is f-ing low man.. It's f-ing LOW.. :/

**Comment by Max-Human** [comment]
"Oh hey everybody there are 'Missing Features' that this guy who is working for free to make awesome free stuff for me to use is several days late in implementing!" :)

I love you Andrew.. :)

**Comment by AndruC** [comment]
Stop getting emotional and defensive. I'm just asking for details on what you do. I get it. You came up with the idea for Human and everything it is. But what is your day-to-day function.

**Comment by Max-Human** [comment]
I'm just having fun man.. :) The short answer to your question is.. "Everything".. :)

**Comment by AndruC** [comment]
Ok, let me break it down to you. I have not invested years of my life into a billion dollar company. I haven't created and sold 5 companies. I don't know what "Everything" is made up of. 

I know you don't code the product. I know you promote it a lot on Facebook. That is all I know.

So, could you, in more detail, and less emotion, give me some examples of things that you do (that only you can do, as the founder) that make up "everything"?

Since you're working 20-hour shifts, you must be doing a lot, so, maybe... 7 things? What are your top 7 priorities to make Human the billion dollar company it is!

Seriously, no need to get emotional. Consider this like an interview. I'm legitimately curious to know. Let me learn from you.

**Comment by Max-Human** [comment]
You have to understand that the IDEA.. is EVERYTHING. The IDEA is the most precious commodity known to man. A single IDEA can be worth a TRILLION dollars. You can HIRE engineers. You can HIRE designers. But an IDEA.. That is PRICELESS.. And the good news is that ANYBODY can come up with one! An example: I have always wanted the profile pictures on our network to be widescreen. I briefly thought about making them animated last year, but forgot all about it. Last week Masha mentioned: widescreen. Now they are widescreen! :) Last night, Bob asked: "do they have sound?" NOW THEY HAVE SOUND! Do you see how this WORKS?.. :)

**Comment by AndruC** [comment]
What would http://www.businessinsider.com/elon-musk-day-in-the-life-of-the-tesla-and-spacex-ceo-2012-7?op=1 this look like, if it were Max Human?

**Comment by AndruC** [comment]
The Idea!  That is uniquely yours, I will admit. Though I don't get how it takes 20 hour shifts. You'd be better off sleeping 8 hours a day and using your waking hours more effectively! The brain needs its rest of course.

Also, here's some [recommended reading](http://sivers.org/multiply)

**Comment by Max-Human** [comment]
There is no emotion man.. You have no idea what I have been through.. :) I am just relaxed and having fun man.. :) I don't know what "emotion" and "defensive" you are referring to.. You are just wasting my time with your silly questions.. :) Instead of CONTRIBUTING, you are TALKING.. :)

**Comment by AndruC** [comment]
Just trying to understand the details of your vision, Max my man. We can't all see things the way you do!

**Comment by Max-Human** [comment]
My top 7 I would say.. #1 is making sure everybody knows what they are doing today. :) And in a week, and in a month, and in 5 years from now.. #2 is making sure is any emergencies (any urgent issues) are handled for today.. #3..

**Comment by Max-Human** [comment]
#3 is making sure everybody performed to their highest level yesterday, making sure everything they did was PERFECT, that any mistakes are handled QUICKLY.

**Comment by Max-Human** [comment]
#4 I would say is making bold moves TODAY, and scheduling bold moves for TOMORROW, to move us FORWARD, in BIG, GIANT STEPS..

**Comment by Max-Human** [comment]
brb phone

**Comment by Max-Human** [comment]
#5 I would say is talking to the PEOPLE and figuring out what THEY want.. :) brb phone again..

**Comment by Max-Human** [comment]
Sorry, had a call with my CTO. :) #6-100 I don't know what they are, let me think about it.. :) It's about to be making contacts with the media - I am gonna call the top 100 media personalities in the world and just say "hey, what's up" and establish a relationsiip. :) Design also has to be WAY up there - I spend a LOT of my time im Photoshop.. Production of our upcoming videos is up there too.. Strategic partnerships with an insane number of companies are there as well.. It's a lot of stuff.. I need to think.. :)

**Comment by rjamesnw** [comment]
#6: Awnsera phones, lol

**Comment by rjamesnw** [comment]
Answers phones - stupid phone keyboard is dyslexic. :/

**Comment by Max-Human** [comment]
Nah I don't answer phones - we're gonna have a few other people for that. :) I don't even answer the calls to my extension lol - my phone is always on silent. I just return messages, if I have to. In the very near future, once we get totally swamped, even my email and voicemail will be checked by an assistant only (there will still be a private email and cell # for those I am well acquainted with though). This is the same system we had set up at one of my previous companies - it's the only way to deal with 100+ emails and phone calls a day.

**Comment by Max-Human** [comment]
Thanks for the links Andrew, I will check em out. :)

**Comment by rjamesnw** [comment]
It was a joke silly - because you were answering your phone earlier! lol

**Comment by Max-Human** [comment]
Hahah that's pretty clever. :D

**Comment by AmaltheCamal** [comment]
I'm confused. You don't seem to do anything specific, yet I see stream after stream of post on every social media site. If you are spending 20 hours a day liking each post on facebook with every other one of your accounts (1 billion humans for astroturf!), who is doing that actual company work?

Is this why nothing ever gets delivered after so many promises?

**Comment by Max-Human** [comment]
We don't seem to do anything specific?

Nothing gets delivered?

Buddy, I'm gonna be as polite as I possibly can be and ask you to take a hike.

I have responded to your other request (waste of time) here:

https://github.com/HumanityInc/Humanity/issues/2

Now do us a favor and go back to where you came from. You are wasting everybody's time here.

**Comment by Max-Human** [comment]
Andrew, everything I said to him in the link above also concerns you. You should read it.

**Comment by AmaltheCamal** [comment]
So... you haven't done anything, then?

**Comment by Max-Human** [comment]
Get a life loser. :)

FYI everybody, this is just the same guy making new accounts and trolling us.
